[build]
  publish = "."

[[redirects]]
  from = "/.well-known/*"
  to = "/well-known/:splat"
  status = 200
  force = true

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"
